operatingRoom:
  temperature: 25.0
  humidity: 55.0
  ambientIlluminance: 100
  surgicalIlluminance: 100000

operatingRoomStandbyMode:
  enabled: yes
  minutesToEnable: 20
  environment:
    temperature: 22.0
    humidity: 55.0
    ambientIlluminance: 50
    surgicalIlluminance: 150

prePostOperatingRoom:
  temperature: 25.0
  humidity: 55.0
  ambientIlluminance: 100

prePostOperatingRoomStandbyMode:
  enabled: yes
  minutesToEnable: 20
  environment:
    temperature: 22.0
    humidity: 55.0
    ambientIlluminance: 50

medicalTechnologyScenarios:
  - medicalTechnologyType: endoscope
    ambientIlluminance: 60
    surgicalIlluminance: 150000